### ISSUE TITLE
Looking for links to JavaDocs and other detailed user guides

### ISSUE THREAD

**Issue by nkolban** [Kong/unirest-website#3]
At the site, I was looking for links for the JavaDoc and other detailed programming guides but was unable to find them.

**Comment by Nijikokun** [comment]
Duplicate of https://github.com/Mashape/unirest-java#69

**Comment by nijikokun** [comment]
Duplicate of https://github.com/Mashape/unirest-java/issues/69

**Comment by nijikokun** [comment]
These pages are autogenerated using the readme of the project, so its better to comment on the project to update it's readme.
